{\bfseries No.\hfill \hfill Equation\hspace {3in} Page No.\vspace \bigskipamount \par }
\contentsline {myequations}{\numberline {1}Mean Absolute Error (MAE)}{103}{equation.3.1}%
\contentsline {myequations}{\numberline {2}Accuracy}{107}{equation.3.2}%
\contentsline {myequations}{\numberline {3}Precision}{107}{equation.3.3}%
\contentsline {myequations}{\numberline {4}Recall}{107}{equation.3.4}%
\contentsline {myequations}{\numberline {5}F1 - Score}{107}{equation.3.5}%
\contentsline {myequations}{\numberline {6}Confusion Matrix}{107}{equation.3.6}%
