{\bfseries No.\hfill \hfill Equation\hspace {3in} Page No.\vspace \bigskipamount \par }
\contentsline {myequations}{\numberline {1}Accuracy}{113}{equation.3.1}%
\contentsline {myequations}{\numberline {2}Precision}{114}{equation.3.2}%
\contentsline {myequations}{\numberline {3}Recall}{114}{equation.3.3}%
\contentsline {myequations}{\numberline {4}F1 - Score}{114}{equation.3.4}%
\contentsline {myequations}{\numberline {5}Confusion Matrix}{114}{equation.3.5}%
